### ISSUE TITLE
RPI with dwc server emu

### ISSUE THREAD

**Issue by PhynixP** [kyle95wm/dwc_network_server_emulator#3]
Hello ,
sorry for my bad english ,i am from germany
your fork of the dwc server ist very nice.
I have a Raspberry pi with Rasbian.
I Start the install script and then the Server.with phyton master-server.py
then i type my external IP in my Wii.
Then i have a error  in my wii

have you any idea ?

**Comment by kyle95wm** [comment]
Which error?

**Comment by PhynixP** [comment]
Hello,
52130 is the error on the wii
IT Works fine With the test Server ip
Am 29.03.2015 16:31 schrieb "Kyle Warwick-Mathieu" <notifications@github.com

**Comment by kyle95wm** [comment]
I have a feeling you misunderstood the external IP. It sounds like you can't reach your server from the external IP because certain ports need to be opened. Run an ifconfig and enter your inet address onto your Wii's DNS. I warn you this script is still in the experimental stages.

**Comment by PhynixP** [comment]
Ok thanks,
But why Dont work IT on local LAN?
I have feeling, the DNS from nintenwii.net to my ip dont work right.
Why ports i must open for the connection?
Am 29.03.2015 18:40 schrieb "Kyle Warwick-Mathieu" <notifications@github.com

**Comment by kyle95wm** [comment]
You know the screen that says "listening for connections" and it has a port number attached to each one. You have to open both TCP and UDP ports from the list to point to your rpi's IP

**Comment by PhynixP** [comment]
Ok thanks for the Infos
I test IT tomorow
Am 29.03.2015 21:29 schrieb "Kyle Warwick-Mathieu" <notifications@github.com

**Comment by PhynixP** [comment]
Hello,
i have been testet the the now with open ports.
I have the same problem :(
Ok.. i have bei the wii dns my inet ip (77.XXX.XXX.XXX)
In my Router i have all Ports from the Master_Server.
Then i have type the 77.XXX.XXX.XXX in my dnsmasq.cfg (address=/nintendowifi.net/77.XXX.XXX.XXX)
My next Step, i type the 77.XXX.XXX.XXX in my Wii in the DNS Settings.
Then i became the errorcode 52130
For test, i have type the 104.131.93.87 from the public testserver in my Wii DNS Settings.
Then the connection is fine and works.

Who is the Problem by me ?

**Comment by kyle95wm** [comment]
It sounds to me like you're trying to use your external IP address on your wii. Unless your Wii isn't ob the same LAN as your Pi, there's no need to use the external IP address but instead use the local address foubd by running ifconfig or your router will tell you the IP your Pi is using. Even though the script asked you what your external IP is it doesn't mean you have to use it on the local network, but its always a good idea to see if the outside world can reach you. 

I'm not exactly sure what the problem is, but make sure DNSMASQ and Apache are running. If all else fails set the DMZ in your router to your Pi (to fully expose the ports)

**Comment by PhynixP** [comment]
My Pi have the IP 192.168.1.20
In my wii i have the ip ....20 in the DNS settings Type ..Same error ;)

But i  think i have Found an error.
The Proxy Module cant find my PI
Mod 1  2  3 the PI cant finden
Mod 4 the PI say  proxy is enabled.
My PI have the newest Raspbian installed.

Can this make my Error ?
 Am 29.03.2015 23:32 schrieb "Kyle Warwick-Mathieu" <
notifications@github.com>:

**Comment by kyle95wm** [comment]
Interesting. mod4 was only intended as a fallback in case mod1,2,3 can't be found on the system (this appears to be the case with OS's like Kali) but I had no problem with setting this stuff up with Raspbian in fact I had to do it all manually. The Apache config files are set up as they should be and not be modified. To be honest, I don't understand whats causing the error. In fact I'm not actually able to test any server right now because of the fact that I have a web server set up on my windows server computer and whenever I go to connect with WFC I get 23404 (http://beanjr.hopto.org/error) but 23404 basically means that it can't find the server (nintendowifi.net files not enabled) but in your case you can't get passed the connection test. Are you able to do an nslookup on your localhost on any of the Nintendo domain names? Sounds like your DNS isn't working

**Comment by PhynixP** [comment]
I have the feeling too, the DNSmasq server have an error, but i can't find this error :(
the Server is running with ''ok'' in the shell.
I haven't any idea more :)

**Comment by kyle95wm** [comment]
Looks like the problem is now solved. Turns out I made 2 mistakes in 1 script
-the virtual host file names were wrong
-I specified the modules incorrectly
